### ISSUE TITLE
Errors running V2 code

### ISSUE THREAD

**Issue by jiacheng-xu** [google-research/FLAN#4]
Hi! Thanks for the open source effort for this project. 
When I am trying to run V2 code, I had two issues: 

1. AESLC checksum error -> I have removed this dataset from configs, which makes the code move forward but breaks the “academic benchmark”
2. ValueError: Mixture, palmflan_flan_zs_opt, does not contain any Tasks.
I can't figure out this error. 

Code I run:
```
import mixtures, task_splits, tasks
dataset = seqio.get_mixture_or_task("flan_inter_cluster_split_0_10templates_train").get_dataset(
    sequence_length={"inputs": 4096, "targets": 4096},
)
```
and 

```
from flan.v2 import constants
from flan.v2 import constants_t0
from flan.v2 import mixtures_utils
from flan.v2 import mixtures
from flan.v2 import tasks  # pylint: disable=unused-import
import seqio
seqio.add_global_cache_dirs(constants.CACHE_DIRS)
seqio.set_global_cache_dirs(constants.CACHE_DIRS)

seqio.MixtureRegistry.add(
    'flan_zs_fs_opt',
    tasks=[
        ('flan_zsopt', 50),  # mixing weight = 50
        ('flan_fsopt', 50),  # mixing weight = 50
])

dataset = seqio.get_mixture_or_task("flan_zs_fs_opt").get_dataset(
    sequence_length={"inputs": 256, "targets": 128},
    split="train",
    shuffle=True,
    num_epochs=1,
    shard_info=seqio.ShardInfo(index=0, num_shards=10),
    use_cached=False,
    seed=42
)

# Print the first 5 examples.
for _, ex in zip(range(5), dataset.as_numpy_iterator()):
  print(ex)
```

Package version:
```
Package                      Version
---------------------------- ---------------------
absl-py                      1.4.0
aiohttp                      3.8.3
aiosignal                    1.3.1
astunparse                   1.6.3
async-timeout                4.0.2
asynctest                    0.13.0
attrs                        21.2.0
Babel                        2.9.1
backports.cached-property    1.0.2
blessed                      1.20.0
bpython                      0.24
cached-property              1.5.2
cachetools                   4.2.2
certifi                      2021.5.30
charset-normalizer           2.0.4
chex                         0.1.5
clang                        5.0
click                        8.0.1
clu                          0.0.8
colorama                     0.4.4
contextlib2                  21.6.0
curtsies                     0.4.1
cwcwidth                     0.1.8
cycler                       0.11.0
datasets                     2.9.0
dill                         0.3.6
dm-tree                      0.1.8
editdistance                 0.5.3
etils                        0.9.0
filelock                     3.0.12
flatbuffers                  23.1.21
flax                         0.6.4
fonttools                    4.38.0
frozendict                   2.3.4
frozenlist                   1.3.3
fsspec                       2023.1.0
future                       0.18.2
gast                         0.4.0
gin-config                   0.4.0
google-auth                  1.35.0
google-auth-oauthlib         0.4.5
google-pasta                 0.2.0
googleapis-common-protos     1.53.0
greenlet                     2.0.2
grpcio                       1.39.0
h5py                         3.1.0
huggingface-hub              0.12.0
idna                         3.2
importlib-metadata           6.0.0
importlib-resources          5.10.2
iniconfig                    1.1.1
jax                          0.3.25
jaxlib                       0.3.25
joblib                       1.0.1
keras                        2.11.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
Levenshtein                  0.13.0
libclang                     15.0.6.1
Markdown                     3.3.4
markdown-it-py               2.1.0
matplotlib                   3.5.3
mdurl                        0.1.2
mesh-tensorflow              0.1.19
ml-collections               0.1.1
msgpack                      1.0.4
multidict                    6.0.4
multiprocess                 0.70.14
nltk                         3.6.2
numpy                        1.21.6
oauthlib                     3.1.1
opt-einsum                   3.3.0
optax                        0.1.4
orbax                        0.1.0
packaging                    21.0
pandas                       1.3.2
Pillow                       9.4.0
pip                          23.0
pluggy                       0.13.1
portalocker                  2.3.0
promise                      2.3
protobuf                     3.17.3
psutil                       5.9.4
py                           1.10.0
pyarrow                      11.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyglove                      0.2.1
Pygments                     2.14.0
pyparsing                    2.4.7
pytest                       6.2.4
python-dateutil              2.8.2
pytz                         2021.1
pyxdg                        0.28
PyYAML                       5.4.1
regex                        2021.8.3
requests                     2.26.0
requests-oauthlib            1.3.0
responses                    0.18.0
rich                         13.3.1
rouge-score                  0.0.4
rsa                          4.7.2
sacrebleu                    2.0.0
sacremoses                   0.0.45
scikit-learn                 0.24.2
scipy                        1.7.1
sentencepiece                0.1.96
seqio                        0.0.14
setuptools                   47.1.0
six                          1.15.0
t5                           0.9.2
tabulate                     0.8.9
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.0
tensorflow                   2.11.0
tensorflow-datasets          4.8.2
tensorflow-estimator         2.11.0
tensorflow-hub               0.12.0
tensorflow-io-gcs-filesystem 0.30.0
tensorflow-metadata          1.12.0
tensorflow-text              2.11.0
tensorstore                  0.1.28
termcolor                    1.1.0
tfds-nightly                 4.8.2.dev202301270045
threadpoolctl                2.2.0
tokenizers                   0.10.3
toml                         0.10.2
toolz                        0.12.0
torch                        1.9.0
tqdm                         4.62.1
transformers                 4.9.2
typing_extensions            4.4.0
urllib3                      1.26.6
wcwidth                      0.2.6
Werkzeug                     2.0.1
wheel                        0.38.4
wrapt                        1.12.1
xxhash                       3.2.0
yarl                         1.8.2
zipp                         3.12.1

```

**Comment by shayne-longpre** [comment]
Thank you for your patience Jiacheng. Could you try updating to the latest version of the repository and starting your environment from the requirements.txt file added to the `v2` folder of the repo? Let us know if that works.

(You may need to comment out the QReCC dataset which still has a fix arriving.)

Thanks!

**Comment by evi-Genius** [comment]
I tried his second paragraph code, but it didn't work. I got _ValueError: Task lambada_template_0to10_x_shot has no splits_ Seems there are some bugs hidden in the repo.

**Comment by jiacheng-xu** [comment]
> Thank you for your patience Jiacheng. Could you try updating to the latest version of the repository and starting your environment from the requirements.txt file added to the `v2` folder of the repo? Let us know if that works.
> 
> (You may need to comment out the QReCC dataset which still has a fix arriving.)
> 
> Thanks!

Thanks for your response!
I tried the updated code with the following code:

```
from flan.v2 import constants
from flan.v2 import constants_t0
from flan.v2 import mixtures_utils
import mixtures, task_splits, tasks
import seqio
seqio.add_global_cache_dirs(constants.CACHE_DIRS)
seqio.set_global_cache_dirs(constants.CACHE_DIRS)
seqio.MixtureRegistry.add(
    'full_cot',
    tasks=[
        ('cot_zsopt', 25),    # mixing weight = 25
        ('cot_fsopt', 25),    # mixing weight = 25
        ('cot_zsnoopt', 25),  # mixing weight = 25
        ('cot_fsnoopt', 25),  # mixing weight = 25
    ])
dataset = seqio.get_mixture_or_task("full_cot").get_dataset(
    sequence_length={"inputs": 256, "targets": 128},
    split="train",
    shuffle=True,
    num_epochs=1,
    shard_info=seqio.ShardInfo(index=0, num_shards=10),
    use_cached=False,
    seed=42
)
```
And I got this error:
```
Traceback (most recent call last):
  File "/export/home/FLAN/flan/v2/run_flan.py", line 8, in <module>
    import mixtures, task_splits, tasks
  File "/export/home/FLAN/flan/v2/mixtures.py", line 90, in <module>
    task_suffixes=constants.TRAIN_TASK_SUFFIXES,
  File "/export/home/FLAN/flan/v2/mixtures_utils.py", line 324, in generate_mixture_suites
    tsuffix, automatic_submix_name)
  File "/export/home/FLAN/flan/v2/mixtures_utils.py", line 198, in register_submixture_variants
    use_all_templates=False,
  File "/export/home/FLAN/flan/v2/mixtures_utils.py", line 139, in register_mixture
    tasks=task_template_ids,
  File "/export/home/venvs/pyflan/lib/python3.7/site-packages/seqio/dataset_providers.py", line 1691, in add
    name, provider_cls=mixture_cls, provider_kwargs=provider_kwargs)
  File "/export/home/venvs/pyflan/lib/python3.7/site-packages/seqio/dataset_providers.py", line 129, in add
    provider = provider_cls(**provider_kwargs)  # pytype: disable=wrong-arg-types  # dynamic-method-lookup
  File "/export/home/venvs/pyflan/lib/python3.7/site-packages/seqio/dataset_providers.py", line 1378, in __init__
    raise ValueError(f"Mixture, {self.name}, does not contain any Tasks.")
ValueError: Mixture, palmflan_flan_zs_opt, does not contain any Tasks.
```

Can you briefly explain why and when `UNIVERSAL_MIX_PREFIX = 'palmflan'` is used? Thanks!

**Comment by jiacheng-xu** [comment]
> 

I also had this issue before. Were you using 'dialog'?
